# Use the official Node.js 14 LTS (Buster) image
FROM node:14-buster

# Set environment variables
ENV NODE_ENV=production

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY ["package.json", "package-lock.json*", "./"]

# Install dependencies
RUN npm install

# Copy the entire application code to the container
COPY . .

# Start the application
CMD [ "node", "index.js" ]
